services:
    meeting:
        class: BBBLoadBalancer\AdminBundle\Service\MeetingService
        arguments: [ @doctrine_mongodb, @validator ]
    server:
        class: BBBLoadBalancer\AdminBundle\Service\ServerService
        arguments: [ @doctrine_mongodb, @bbb, @validator, @meeting, @logger ]
    recording:
        class: BBBLoadBalancer\AdminBundle\Service\RecordingService
        arguments: [ @doctrine_mongodb, @validator ]